name: Run Android Tests with Appium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instalar dependências do projeto
      - name: Install dependencies
        run: npm install

      # 4. Configurar emulador Android
      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: adb devices

      # 5. Instalar o Appium
      - name: Install Appium
        run: npx appium driver install uiautomator2

      # 6. Iniciar o servidor Appium
      - name: Start Appium Server
        run: npx appium --log-level error &
        env:
          PATH: ${{ env.PATH }}:./node_modules/.bin

      # 7. Executar os testes com WebdriverIO
      - name: Run Tests
        run: npm test

      # 8. Gerar e armazenar relatórios Allure (opcional)
      - name: Generate Allure Report
        run: npm run allure

      # 9. Fazer upload de relatórios Allure como artifacts
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
