name: Run Cypress Tests and Generate HTML Report

on:
  push:
    branches:
      - main  # Ou a branch em que você deseja rodar os testes
  pull_request:
    branches:
      - main  # Ou a branch em que você deseja rodar os testes

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Ou outro ambiente conforme necessário

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar dependências do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Altere para a versão do Node que você está utilizando

      - name: Install dependencies
        run: |
          cd UI
          npm install  # Instala as dependências definidas no package.json

      # Rodar os testes Cypress
      - name: Run Cypress tests
        run: |
          cd UI
          npm run test  # Executa os testes Cypress

      # Verificar se o relatório foi gerado
      - name: List reports directory
        run: |
          cd UI
          ls -l ./cypress/reports/mochawesome  # Verifica se o arquivo HTML ou JSON foi gerado

      # Gerar o relatório HTML diretamente (sem usar JSON)
      - name: Generate Mochawesome HTML report
        run: |
          cd UI
          npx mochawesome-report-generator ./cypress/reports/mochawesome/*.json --reportDir ./cypress/reports/mochawesome --reportFilename report.html

      # Publicar o relatório no GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: UI/cypress/reports/mochawesome
